[package]
name = "erio-embedding"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Embedding engine for Erio"

[dependencies]

[lints]
workspace = true
